name: Docker Build and push
run-name: ${{ github.actor }} has triggered the pipeline
on: 
  push:
    branches:
      - main

env:
  SERVICE_NAME: ${{ github.repository_owner }} 

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: check vars
        shell: bash
        run: |
          echo ${{ env.SERVICE_NAME }}
          echo ${{ github.repository }}
          echo ${{ github.event.repository.name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tahsib/node-test-app:${{github.workflow_sha}}
          build-args: |

