name: Docker Build and push
run-name: ${{ github.actor }} has triggered the pipeline
on: 
  push:
    branches:
      - main
jobs:
  docker-build-push:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tahsib/node-test-app:${{github.workflow_sha}}
          build-args: |

