name: Docker Build and push
run-name: ${{ github.actor }} has triggered the pipeline
on: 
  push:
    branches:
      - main

env:
  SERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: check vars
        id: tags
        shell: bash
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.repository }}
          echo ${{ env.SERVICE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract tags
        shell: bash
        run: |
          TAGS=$(echo "inte,prep" | tr ',' '\n')
          echo 'TAGS_ENV<<EOF' >> $GITHUB_ENV
          for line in $TAGS; do
            echo -e "$line\n" >> $GITHUB_ENV
          done
          echo 'EOF' >> $GITHUB_ENV
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "tahsib/node-test-app"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            "{{ env.TAGS_ENV }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |

